name: video_gen_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  font_awesome_flutter: 10.9.1
  google_sign_in: ^6.1.5
  shared_preferences: ^2.5.3
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  http_parser: ^4.1.2
  http: ^1.2.2
  video_player: ^2.10.0
  chewie: ^1.13.0
  path_provider: ^2.1.4
  device_info_plus: ^10.1.2
  permission_handler: ^11.0.1
  dio: ^5.4.0
  gal: ^2.3.0
  flutter_sound: ^9.2.13
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/bottom-bar-icon/
    - images/bottom-bar-icon/dashboard.png
    - images/bottom-bar-icon/my-avatar.png
    - images/bottom-bar-icon/create-new-video.png
    - images/bottom-bar-icon/projects.png
    - images/bottom-bar-icon/settings.png
    - images/logo.png
    - images/slider-image-1.png
    - images/slider-image-2.png
    - images/slider-image-3.png
    - images/slider-icon-1.png
    - images/slider-icon-2.png
    - images/slider-icon-3.png
    - images/credit-icon.png
    - images/money-icon.png
    - images/project-icon.png
    - images/completed-icon.png
    - images/download-icon.png
    - images/delete-icon.png
    - images/text-icon.png
    - images/avatar-icon.png
    - images/splash-logo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  adaptive_icon_background: "#16162D"
  adaptive_icon_foreground: "images/logo.png"
  remove_alpha_ios: true

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#16162D"
  image: "images/logo.png"
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
